//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.21 at 09:24:08 AM UTC 
//


package app.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tessera" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="punti" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="data_di_creazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sede_di_creazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="cliente"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="cognome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="numero_tessera" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tessera"
})
@XmlRootElement(name = "tessere")
public class Tessere {

    @Override
    public String toString() {
        StringBuilder str = new StringBuilder("Tessere {\n");
        if (tessera.isEmpty()) {
            str.append("\tNessuna tessera disponibile.\n");
        } else {
            for (Tessera t : tessera) {
                str.append(t.toString()).append("\n");
            }
        }
        str.append("}");
        return str.toString();
    }


    @XmlElement(required = true)
    protected List<Tessere.Tessera> tessera;

    /**
     * Gets the value of the tessera property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tessera property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTessera().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tessere.Tessera }
     * 
     * 
     */
    public List<Tessere.Tessera> getTessera() {
        if (tessera == null) {
            tessera = new ArrayList<Tessere.Tessera>();
        }
        return this.tessera;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="punti" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="data_di_creazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sede_di_creazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="cliente"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="cognome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="numero_tessera" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "punti",
        "dataDiCreazione",
        "sedeDiCreazione",
        "cliente"
    })
    public static class Tessera {

        @Override
        public String toString() {
            return new StringBuilder("\tTessera [Punti=")
                    .append(punti)
                    .append(", DataDiCreazione=")
                    .append(dataDiCreazione)
                    .append(", SedeDiCreazione=")
                    .append(sedeDiCreazione)
                    .append(", ")
                    .append(cliente)
                    .append(", NumeroTessera=")
                    .append(numeroTessera)
                    .append("]")
                    .toString();
        }


        @XmlSchemaType(name = "integer")
        protected int punti;
        @XmlElement(name = "data_di_creazione", required = true)
        protected String dataDiCreazione;
        @XmlElement(name = "sede_di_creazione", required = true)
        protected String sedeDiCreazione;
        @XmlElement(required = true)
        protected Tessere.Tessera.Cliente cliente;
        @XmlAttribute(name = "numero_tessera", required = true)
        protected BigInteger numeroTessera;

        /**
         * Gets the value of the punti property.
         * 
         */
        public int getPunti() {
            return punti;
        }

        /**
         * Sets the value of the punti property.
         * 
         */
        public void setPunti(short value) {
            this.punti = value;
        }

        /**
         * Gets the value of the dataDiCreazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataDiCreazione() {
            return dataDiCreazione;
        }

        /**
         * Sets the value of the dataDiCreazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataDiCreazione(String value) {
            this.dataDiCreazione = value;
        }

        /**
         * Gets the value of the sedeDiCreazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSedeDiCreazione() {
            return sedeDiCreazione;
        }

        /**
         * Sets the value of the sedeDiCreazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSedeDiCreazione(String value) {
            this.sedeDiCreazione = value;
        }

        /**
         * Gets the value of the cliente property.
         * 
         * @return
         *     possible object is
         *     {@link Tessere.Tessera.Cliente }
         *     
         */
        public Tessere.Tessera.Cliente getCliente() {
            return cliente;
        }

        /**
         * Sets the value of the cliente property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tessere.Tessera.Cliente }
         *     
         */
        public void setCliente(Tessere.Tessera.Cliente value) {
            this.cliente = value;
        }

        /**
         * Gets the value of the numeroTessera property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumeroTessera() {
            return numeroTessera;
        }

        /**
         * Sets the value of the numeroTessera property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumeroTessera(BigInteger value) {
            this.numeroTessera = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="cognome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nome",
            "cognome",
            "mail"
        })
        public static class Cliente {

            @Override
            public String toString() {
                return new StringBuilder("Cliente (Nome=")
                        .append(nome)
                        .append(", Cognome=")
                        .append(cognome)
                        .append(", Mail=")
                        .append(mail)
                        .append(", ID=")
                        .append(id)
                        .append(")")
                        .toString();
            }

            @XmlElement(required = true)
            protected String nome;
            @XmlElement(required = true)
            protected String cognome;
            @XmlElement(required = true)
            protected String mail;
            @XmlAttribute(name = "id", required = true)
            protected BigInteger id;

            /**
             * Gets the value of the nome property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNome() {
                return nome;
            }

            /**
             * Sets the value of the nome property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNome(String value) {
                this.nome = value;
            }

            /**
             * Gets the value of the cognome property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCognome() {
                return cognome;
            }

            /**
             * Sets the value of the cognome property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCognome(String value) {
                this.cognome = value;
            }

            /**
             * Gets the value of the mail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMail() {
                return mail;
            }

            /**
             * Sets the value of the mail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMail(String value) {
                this.mail = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

        }

    }

}
